services:
    api-server:
        build:
            context: ./backend/api/
            dockerfile: Dockerfile
        env_file:
            - ./.env
        ports:
            - "8000:8000"
        networks:
            - internal
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:17
        environment:
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DATABASE: "${DB_NAME}"
            POSTGRES_ROOT_PASSWORD: root
        ports:
            - "${DB_PORT}:${DB_PORT}"
        networks:
            - internal
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U gityard -d gityard"]
            interval: 5s
            timeout: 5s
            retries: 5

networks:
    internal:
        driver: bridge
