services:
    # api-server:
    #     build:
    #         context: ./backend/api/
    #         dockerfile: Dockerfile
    #     env_file:
    #         - ./.env
    #     ports:
    #         - "8000:8000"
    #     networks:
    #         - internal
    #     depends_on:
    #         database:
    #             condition: service_healthy
    api-server2:
        build:
            context: ./backend/api2/
            dockerfile: Dockerfile
        env_file:
            - ./.env
        ports:
            - "8000:8000"
        networks:
            - internal
        depends_on:
            database:
                condition: service_healthy

    database:
        image: mysql:8.0
        environment:
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./database/init:/docker-entrypoint-initdb.d
        ports:
            - "${DB_PORT}:${DB_PORT}"
        networks:
            - internal
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    internal:
        driver: bridge
